baseURL = '/'
languageCode = 'en-us'
title = 'digital.auto playground documentation'

theme = 'hugo-theme-relearn'
[params]
  custom_css = ["css/playground.css"]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
themeVariant = "green"
disableLandingPageButton = true
showVisitedLinks = true

editURL = "https://github.com/eclipse-autowrx/docs/blob/main/content/"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[services]
  [services.googleAnalytics]
    ID = 'G-QSPHHE9ZTS'


[[menu.shortcuts]] 


name = "<i class='fas fa-github'></i> Github repo"
url = "https://github.com/eclipse-autowrx"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-camera'></i> Showcases"
url = "https://www.youtube.com/@sdvpg"
weight = 11
